version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/common/docker/snapclient"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/common/docker/audio-visualizer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/common/docker/fb-display"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
