# Allo Boss DAC Configuration
HAT_NAME="Allo Boss DAC"
HAT_OVERLAY="allo-boss-dac-pcm512x-audio"
HAT_CARD_NAME="BossDAC"
HAT_TYPE="analog"
HAT_FORMAT="S32_LE"
HAT_RATE="192000"
HAT_MIXER="hardware:Digital"
