# HiFiBerry DAC+ ADC Pro Configuration
HAT_NAME="HiFiBerry DAC+ ADC Pro"
HAT_OVERLAY="hifiberry-dacplusadcpro"
HAT_CARD_NAME="sndrpihifiberry"
HAT_TYPE="analog"
HAT_FORMAT="S32_LE"
HAT_RATE="192000"
HAT_MIXER="hardware:Digital"
