# HiFiBerry DAC2 HD Configuration
HAT_NAME="HiFiBerry DAC2 HD"
HAT_OVERLAY="hifiberry-dacplushd"
HAT_CARD_NAME="sndrpihifiberry"
HAT_TYPE="analog"
HAT_FORMAT="S32_LE"
HAT_RATE="192000"
HAT_MIXER="hardware:Digital"
