# IQaudio DigiAMP+ Configuration
HAT_NAME="IQaudio DigiAMP+"
HAT_OVERLAY="iqaudio-digiampplus"
HAT_CARD_NAME="IQaudIODAC"
HAT_TYPE="analog"
HAT_FORMAT="S32_LE"
HAT_RATE="48000"
HAT_MIXER="hardware:Digital"
