# IQaudio Codec Zero Configuration
HAT_NAME="IQaudio Codec Zero"
HAT_OVERLAY="iqaudio-codec"
HAT_CARD_NAME="IQaudIOCODEC"
HAT_TYPE="analog"
HAT_FORMAT="S16_LE"
HAT_RATE="48000"
HAT_MIXER="hardware:Headphone"
